// desktop/src/components/shared/Button.svelte
<script lang="ts">
  export let variant: 'primary' | 'secondary' | 'danger' = 'secondary';
  export let size: 'normal' | 'small' = 'normal';
  export let disabled = false;
  export let type: 'button' | 'submit' = 'button';
</script>

<button
  {type}
  {disabled}
  class:primary={variant === 'primary'}
  class:danger={variant === 'danger'}
  class:small={size === 'small'}
  on:click
>
  <slot />
</button>

<style>
  button {
    cursor: pointer;
    border: none;
    background: var(--bg-tertiary);
    color: var(--text-primary);
    padding: 8px 16px;
    border-radius: 4px;
    font-size: 14px;
    transition: background 0.2s, opacity 0.2s;
    display: inline-flex;
    align-items: center;
    gap: 6px;
  }

  button:hover:not(:disabled) {
    background: var(--border-color);
  }

  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  button.primary {
    background: var(--accent-primary);
    color: var(--bg-primary);
  }

  button.primary:hover:not(:disabled) {
    background: #00b8d9;
  }

  button.danger {
    background: var(--accent-error);
    color: white;
  }

  button.danger:hover:not(:disabled) {
    background: #cc3333;
  }

  button.small {
    padding: 4px 10px;
    font-size: 12px;
  }
</style>

// src/components/ui/button.tsx
import * as React from 'react';
import { Slot } from '@radix-ui/react-slot';
import { cva, type VariantProps } from 'class-variance-authority';
import { cn } from './cn';

const buttonVariants = cva(
  'inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50',
  {
    variants: {
      variant: {
        default: 'bg-primary text-primary-foreground hover:opacity-90',
        secondary: 'bg-secondary text-secondary-foreground hover:opacity-90',
        ghost: 'hover:bg-muted',
        destructive: 'bg-destructive text-destructive-foreground hover:opacity-90',
      },
      size: {
        sm: 'h-8 px-3',
        md: 'h-9 px-4',
        lg: 'h-10 px-5',
      },
    },
    defaultVariants: {
      variant: 'default',
      size: 'md',
    },
  },
);

export interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean;
}

export const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild, ...props }, ref) => {
    const Comp = asChild ? Slot : 'button';
    return <Comp className={cn(buttonVariants({ variant, size }), className)} ref={ref} {...props} />;
  },
);
Button.displayName = 'Button';
